-- MySQL Script generated by MySQL Workbench
-- Thu 14 Jun 2018 11:12:32 AM PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema citalum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema citalum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `citalum` DEFAULT CHARACTER SET utf8 ;
USE `citalum` ;

-- -----------------------------------------------------
-- Table `citalum`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `citalum`.`user` ;

CREATE TABLE IF NOT EXISTS `citalum`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `uo_email` VARCHAR(32) NULL,
  `other_email` VARCHAR(64) NULL,
  `password` VARCHAR(32) NULL,
  `major` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citalum`.`newsletter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `citalum`.`newsletter` ;

CREATE TABLE IF NOT EXISTS `citalum`.`newsletter` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `contents` LONGTEXT NULL,
  `author` VARCHAR(45) NULL,
  `publish_date` DATETIME NULL,
  `title` VARCHAR(45) NULL,
  `subtitle` VARCHAR(45) NULL,
  PRIMARY KEY (`post_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `citalum`.`newsletter`
-- -----------------------------------------------------
START TRANSACTION;
USE `citalum`;
INSERT INTO `citalum`.`newsletter` (`post_id`, `contents`, `author`, `publish_date`, `title`, `subtitle`) VALUES (1, 'Lorem ipsum dolor amet bitters pork belly chambray, cold-pressed magna tacos et. Semiotics 3 wolf moon aesthetic hot chicken irony reprehenderit, keffiyeh taxidermy literally. Poutine tattooed letterpress irure authentic echo park, shabby chic locavore qui freegan. Adaptogen tbh cornhole culpa. Asymmetrical ea shaman before they sold out, fugiat occupy gluten-free heirloom. Messenger bag bushwick schlitz flexitarian. Aesthetic lumbersexual blog live-edge la croix shabby chic 8-bit.\n\nCommodo culpa ugh, wolf kombucha cardigan in sunt salvia freegan pariatur adipisicing taiyaki. Cillum ad tote bag, quinoa shabby chic excepteur craft beer palo santo tbh esse vexillologist sint pug mollit. Bicycle rights woke ullamco next level salvia narwhal tacos keffiyeh four loko. Flannel hella pok pok ramps, actually brooklyn ipsum sustainable small batch portland skateboard lorem. Occupy gentrify flannel, proident cold-pressed cray veniam fam tousled shaman leggings craft beer unicorn.', 'hipsum.co', '2018-06-14', 'Lorem ipsum', 'Lorem ipsum dolor amet');

COMMIT;

